In [1]:
import pandas as pd
import numpy as np

In [2]:
x = pd.Series([[1, 2, 3], [2, 3, 'hi']])
y = np.array([[1, 2, 3], [4, 5, 6]])

First column printed is the Index.
The next columns are the values itself.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

In [3]:
print(f'{type(x)}:\n{x}\n')
print(f'{type(y)}:\n{y}\n')

<class 'pandas.core.series.Series'>:
0     [1, 2, 3]
1    [2, 3, hi]
dtype: object

<class 'numpy.ndarray'>:
[[1 2 3]
 [4 5 6]]



Printing the NDArray of the Series, `x`, and it's `x.shape`

In [4]:
print(type(x.to_numpy()),':')
print(x.to_numpy())
print(f"Shape: {x.to_numpy().shape}")

<class 'numpy.ndarray'> :
[list([1, 2, 3]) list([2, 3, 'hi'])]
Shape: (2,)


`.tolist()` method in PD series turns a series into a list where each row of the series is an element of the list.

In [5]:
x_list = x.tolist()
print(x_list)
arr = np.array(x.tolist())
print(arr)

[[1, 2, 3], [2, 3, 'hi']]
[['1' '2' '3']
 ['2' '3' 'hi']]


Note how we can't have an ndarray of multiple types, so the numbers automatically get converted into strings

`.tail()` and `head()` returns the first and last 5 elements respectively. As default. Or you can set a custom return value.

In [6]:
x = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(f"Head:\n{x.head()}\n")
print(f"Tail:\n{x.tail()}\n")
print(f"First 3:\n{x.head(3)}")

Head:
0    1
1    2
2    3
3    4
4    5
dtype: int64

Tail:
5     6
6     7
7     8
8     9
9    10
dtype: int64

First 3:
0    1
1    2
2    3
dtype: int64


We can also make a series from a dictionary where the keys in the dict get converted into the indices.

In [7]:
data = {'One': 1, 'Two': 2, 'Three': 3}
y = pd.Series(data)
print(y)

One      1
Two      2
Three    3
dtype: int64


In [8]:
x = pd.Series(['goku', 'vegeta', 'broly'], dtype = 'string')
print(x)

0      goku
1    vegeta
2     broly
dtype: string


Then you can also make a series from an ndarray.

Note that an ndarray with $n > 1$ dimensions has be flattened to 1d $(n = 1)$ to be turnt into a series.

A series is a one-dimensional obejct that can hold any data type. It is part of a bigger `pd.DataFrame`.

In [30]:
x = np.array([[[1, 2, 3], [10, 11, 10]], [[0, 1, 3], [5, 2, 3]]])
print(f"X_array:\n{x}")
print(f"Shape:{x.shape}\n")
print(f'X_series:\n{pd.Series(x.flatten().tolist())}\n')
print(f"Shape: {pd.Series(x.flatten().tolist()).shape}")

X_array:
[[[ 1  2  3]
  [10 11 10]]

 [[ 0  1  3]
  [ 5  2  3]]]
Shape:(2, 2, 3)

X_series:
0      1
1      2
2      3
3     10
4     11
5     10
6      0
7      1
8      3
9      5
10     2
11     3
dtype: int64

Shape: (12,)


In [16]:
print(f"ndarray:\n{np.linspace(start = 0, stop = 10, num = 20)}\n")
print(f"pdseries:\n{pd.Series(np.linspace(start = 0, stop = 10, num = 20))}\n")

ndarray:
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]

pdseries:
0      0.000000
1      0.526316
2      1.052632
3      1.578947
4      2.105263
5      2.631579
6      3.157895
7      3.684211
8      4.210526
9      4.736842
10     5.263158
11     5.789474
12     6.315789
13     6.842105
14     7.368421
15     7.894737
16     8.421053
17     8.947368
18     9.473684
19    10.000000
dtype: float64

