## Quickstart

This is my playground, for learning torch, based on PyTorch's tutorials, 'Quickstart'

Check it out [here](https://pytorch.org/tutorials/beginner/basics/intro.html)

In [ ]:
import torch
import numpy as np
import random
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

import shutil


In [2]:
datasets.MNIST(root = '.', train = True, download = True)

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:07<00:00, 1361301.17it/s]


Extracting ./MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 339663.90it/s]


Extracting ./MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:01<00:00, 1221291.67it/s]


Extracting ./MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 5593226.30it/s]

Extracting ./MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST/raw



Dataset MNIST
    Number of datapoints: 60000
    Root location: .
    Split: Train

In [3]:
train = datasets.MNIST(root = '.', train = True, transform=ToTensor())
test = datasets.MNIST(root = '.', train = False, transform=ToTensor())


In [4]:
print(train)

Dataset MNIST
    Number of datapoints: 60000
    Root location: .
    Split: Train
    StandardTransform
Transform: ToTensor()


In [5]:
train_loader = DataLoader(train, batch_size = 3, shuffle = False)

batches = list(train_loader)
first_batch = batches[0]

samples, labels = first_batch

print(f"Sample labels: {labels}")
print(f"Sample Tensors Shape: {samples.shape} | DIMS: (3 (batch dim), 1 (# rgb channel), 28 (rows), 28 (cols))")
print(f"Sample Tensors, first 2 rows: {samples[:, :, :3, :]}")

Sample labels: tensor([5, 0, 4])
Sample Tensors Shape: torch.Size([3, 1, 28, 28]) | DIMS: (3 (batch dim), 1 (# rgb channel), 28 (rows), 28 (cols))
Sample Tensors, first 2 rows: tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.]]],


     

## Working with Data

Pytorch has domain specific libs, such as `torchtext`, `torchvision`, and `torchaudio`. 

Each has utils, pretrained models, preprocessing tools, etc for the respective text, vision, and audio domains.

`torch` provides the overarching api for deeplearning tasks.

In [6]:
training_data = datasets.MNIST(root = 'data', train = True, download = True)

We'd have to transform a given sample to a Tensor as such, if we download without the `transform = ToTensor()`.

It's easier to download the dataset with `transform = ToTensor()` if you're going to preprocess it anyway. Then you don't take up as much memory and the samples are already stored on your hard drive without taking up cpu space.

In [7]:
sample, label = training_data[0]

tensor = ToTensor()

print(f"Label: {label}")
print(f"Sample: {tensor(sample)}")

Label: 5
Sample: tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000

In [8]:
shutil.rmtree('data/MNIST')

# Downloading with transform = ToTensor()

training_data = datasets.MNIST(root = 'data', train = True, download = True, transform = ToTensor())

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:08<00:00, 1215845.45it/s]


Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 261378.13it/s]


Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:01<00:00, 1169523.42it/s]


Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 8410829.48it/s]

Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw



Then, we can directly index the training data

In [9]:
sample, label = training_data[0]

print(f"Label : {label}")
print(f"Sample Tensor Shape: {sample.shape} | DIMS: (RGB Channel, Cols, Rows)")
print(f"Sample Tensor Head(5, axis = 1):\n{sample[:, :5, :]}")

Label : 5
Sample Tensor Shape: torch.Size([1, 28, 28]) | DIMS: (RGB Channel, Cols, Rows)
Sample Tensor Head(5, axis = 1):
tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0.]]])


And you can get batches of data as:

In [10]:
batches = DataLoader(dataset = training_data, batch_size = 5, shuffle = False)

# via list indexing

'''
batches = list(batches)
samples, labels = batches[0]
'''

# via next(iter())

first_batch = next(iter(batches))
samples, labels = first_batch

print(f"Labels: {', '.join([str(label.item()) for label in labels])}")
print(f"Sample Tensor Shape: {samples.shape}")
print(f"Sample Tensor, first row each:\n{samples[:, :, :1, :]}")



Labels: 5, 0, 4, 1, 9
Sample Tensor Shape: torch.Size([5, 1, 28, 28])
Sample Tensor, first row each:
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0.]]]])


`IntTensor.item()` converts the scalar tensor into an int.

`tensor.tolist()` converts a tensor into a list or a nested list of lists.

In [11]:
tensor_scalar = torch.tensor([1])
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
tensor_2d = torch.tensor([[1, 2, 3, 4, 5], [4, 5, 6, 7, 8]])

print(f"Tensor scalar to regular int: {tensor_scalar.item()}")
print(f"1D-tensor to list: {tensor_1d.tolist()}")
print(f"2D-tensor to list: {tensor_2d.tolist()}")

Tensor scalar to regular int: 1
1D-tensor to list: [1, 2, 3, 4, 5]
2D-tensor to list: [[1, 2, 3, 4, 5], [4, 5, 6, 7, 8]]


In [12]:
batch_size = 64

train_dataloader = DataLoader(training_data, batch_size = batch_size)

for X, y in train_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape, dtype of y: {y.shape} {y.dtype}")
    break


Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape, dtype of y: torch.Size([64]) torch.int64


## Creating Models

In [28]:
# get the device you want for training your model

device = (
        'cuda' 
        if torch.cuda.is_available()
        else 'mps' if torch.backends.mps.is_available()
        else'cpu'
        )

print(f"DEVICE: {device}")
if device == 'mps':
    print(f"I have apple m1 lol")


DEVICE: mps
I have apple m1 lol


`nn.Module` class is the base class for defining any neural network. you inherit it's attributes and methods in a subclass, to then build your neural network.

In [33]:
class NN(nn.Module): # inherting from nn.Module class
    def __init__(self):
        super().__init__() # initializing the inherited class
        # any `nn.(layer)` is from torch.nn 
        self.flatten = nn.Flatten() # layer to flatten the input
        self.linear_relu_stack = nn.Sequential( # sequential layer for pure feed forward models
            nn.Linear(784, 512), # layer of linear combinations, comprised of 512 neurons
            nn.ReLU(), # applies ReLU() = max(0, z)
            nn.Linear(512, 512), # 2nd layer of linear combinations, comprised of 512 neurons
            nn.ReLU(), # applies ReLU() = max(0, z)
            nn.Linear(512, 10) # output layer, for 10 output probabilities
        ) 
        
    def forward(self, x): # define the forward pass
        x = self.flatten(x) # pass through the flattening layer
        logits = self.linear_relu_stack(x) # pass through the main model to get the logits prior to final softmax activation
        return logits
   
model = NN().to(device)  # isntantiate the model and send it over to `mps`
print(f'using {device}, haha')
print(f"Our model, for MNIST\n\n{model}")

using mps, haha
Our model, for MNIST

NN(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


#### `nn.Flatten()` and `torch.flatten()`

In [22]:
torch.manual_seed(0)

tensor = torch.randn(2, 2, 2, 2)

print(f"Original tensor shape: {tensor.shape}")
print(f"Original tensor:\n{tensor}\n")

flatten = nn.Flatten(start_dim = 1, end_dim = 2)
flattened_tensor = flatten(tensor)

print(f"Flattened tensor shape:{flattened_tensor.shape}")
print(f"Flattend Tensor:\n{flattened_tensor}")


Original tensor shape: torch.Size([2, 2, 2, 2])
Original tensor:
tensor([[[[-1.1258, -1.1524],
          [-0.2506, -0.4339]],

         [[ 0.8487,  0.6920],
          [-0.3160, -2.1152]]],


        [[[ 0.3223, -1.2633],
          [ 0.3500,  0.3081]],

         [[ 0.1198,  1.2377],
          [ 1.1168, -0.2473]]]])

Flattened tensor shape:torch.Size([2, 4, 2])
Flattend Tensor:
tensor([[[-1.1258, -1.1524],
         [-0.2506, -0.4339],
         [ 0.8487,  0.6920],
         [-0.3160, -2.1152]],

        [[ 0.3223, -1.2633],
         [ 0.3500,  0.3081],
         [ 0.1198,  1.2377],
         [ 1.1168, -0.2473]]])


In [24]:
torch.manual_seed(0)

tensor = torch.randn(2, 2, 2, 2)

print(f"Original tensor shape: {tensor.shape}")
print(f"Original tensor:\n{tensor}\n")

flattened_tensor = torch.flatten(tensor, start_dim = 1, end_dim = 2)

print(f"Flattened tensor shape: {flattened_tensor.shape}")
print(f"Flattened tensor:\n{flattened_tensor}")

Original tensor shape: torch.Size([2, 2, 2, 2])
Original tensor:
tensor([[[[-1.1258, -1.1524],
          [-0.2506, -0.4339]],

         [[ 0.8487,  0.6920],
          [-0.3160, -2.1152]]],


        [[[ 0.3223, -1.2633],
          [ 0.3500,  0.3081]],

         [[ 0.1198,  1.2377],
          [ 1.1168, -0.2473]]]])

Flattened tensor shape: torch.Size([2, 4, 2])
Flattened tensor:
tensor([[[-1.1258, -1.1524],
         [-0.2506, -0.4339],
         [ 0.8487,  0.6920],
         [-0.3160, -2.1152]],

        [[ 0.3223, -1.2633],
         [ 0.3500,  0.3081],
         [ 0.1198,  1.2377],
         [ 1.1168, -0.2473]]])
