In [1]:
import numpy as np

W = np.random.randint(1,9, size = (2, 3)) # neurons, weights
X = np.random.randint(1,9, size = (3, 4)) # samples, features

## Dot Product

In [2]:
print("Weights:")
print(W)

print("Inputs:")
print(f"{X} \n")

print(f"{W.T} \n * \n {X}")

Weights:
[[3 5 7]
 [3 3 2]]
Inputs:
[[6 8 3 8]
 [6 5 7 3]
 [3 3 6 8]] 

[[3 3]
 [5 3]
 [7 2]] 
 * 
 [[6 8 3 8]
 [6 5 7 3]
 [3 3 6 8]]


In [36]:
print(np.dot(W, X))

[[34 50 17 33]
 [31 20 15 25]]


The cell below doesn't work out as the number of columns in matrix $X$ doesn't match with the number of rows in matrix $W$

In [44]:
print(np.dot(X, W))

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)