In [1]:
import numpy as np

gamma = np.ones(shape = (10, 10))

print(gamma)
print(gamma.shape)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
(10, 10)


In [2]:
x = np.random.randn(10, 2)

f = lambda x: 1/(1+ np.exp(x))

print(f(x))

[[0.48559806 0.88136515]
 [0.13696154 0.47950922]
 [0.60680524 0.06028917]
 [0.42291484 0.51683314]
 [0.30261753 0.54664849]
 [0.90245575 0.23688647]
 [0.5140031  0.74587996]
 [0.3604867  0.83636213]
 [0.39151707 0.74361458]
 [0.35760522 0.22882627]]
